version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"

  web:
    build: .
    command: rails s -p 3333 -b '0.0.0.0'
    volumes:
      - .:/app_name
    ports:
      - "3333:3333"
    links:
      - db
